openapi: 3.0.0

info:
  version: 1.0.0
  title: "Players Gambit Web API"
  description: "Web Resources Specification (A7) for Players Gambit."

tags:
  - name: "M01: Authentication"
  - name: "M02: User profile"
  - name: "M03: Administrator"
  - name: "M04: Auctions and Bids"
  - name: "M05: Chat"

paths:
  /login:
    get:
      operationId: R101
      summary: "R101: Login Form"
      description: "Provide login form. Access: VST"
      tags:
        - "M01: Authentication"
      responses:
        "200":
          description: "Ok. Show log-in UI"
    post:
      operationId: R102
      summary: "R102: Login Action"
      description: "Perform the login form submission. Access: VST"
      tags:
        - "M01: Authentication"

      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                email:
                  type: string
                pasword:
                  type: string
              required:
                - email
                - password

      responses:
        "302":
          description: "Redirect after processing the login credentials."
          headers:
            Location:
              schema:
                type: string
              examples:
                302Success:
                  description: "Authentication was Successful. Redirect to main page."
                  value: "/mainpage"
                302Error:
                  description: "Authentication Failed. Redirect to login form."
                  value: "/login"

  /logout:
    post:
      operationId: R103
      summary: "R103: Logout Action"
      description: "Logout the current Authenticated User. Access: USR"
      tags:
        - "M01: Authentication"
      responses:
        "302":
          description: "Redirect after processing logout."
          headers:
            Location:
              schema:
                type: string
              examples:
                302Success:
                  description: "Successful logout. Redirect to login form."
                  value: "/login"

  /register:
    get:
      operationId: R104
      summary: "R104: Register Form"
      description: "Provide user registration form. Access: VST"
      tags:
        - "M01: Authentication"
      responses:
        "200":
          description: "Show sign-up UI."
    post:
      operationId: R105
      summary: "R105: Register Action"
      description: "Processes the new user registration form submission. Access: VST"
      tags:
        - "M01: Authentication"

      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
                profile_pic:
                  type: string
                  format: binary
              required:
                - name
                - username
                - email
                - password

      responses:
        "302":
          description: "Redirect after processing the new user information."
          headers:
            Location:
              schema:
                type: string
              examples:
                302Success:
                  description: "Successful authentication. Redirect to user profile."
                  value: "/users/{id}"
                302Failure:
                  description: "Failed authentication. Redirect to sign up form"
                  value: "/register"

  /users/{id}:
    get:
      operationId: R201
      summary: "R201: View user profile"
      description: "Show the individual user profile. Access: USR"
      tags:
        - "M02: User profile"

      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true

      responses:
        "200":
          description: "Show view profile UI"

  /users/{id}/edit:
    get:
      operationId: R202
      summary: "R202: Edit Profile Form"
      description: "Provide edit profile form. Access: USR"
      tags:
        - "M02: User profile"
      responses:
        "200":
          description: "Show edit profile UI."
    post:
      operationId: R203
      summary: "R203: Edit Profile Action"
      description: "Processes the edit profile form submission. Access: USR"
      tags:
        - "M02: User profile"

      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
                profile_pic:
                  type: string
                  format: binary

      responses:
        "302":
          description: "Redirect after processing the edit profile information."
          headers:
            Location:
              schema:
                type: string
              examples:
                302Success:
                  description: "Successful profile edited. Redirect to user profile."
                  value: "/users/{id}"
                302Failure:
                  description: "Failed profile edited. Redirect to same edit profile page"
                  value: "/users/{id}/edit"

  /admin/deactivateUser:
    post:
      operationId: R301
      summary: "R301- Deactivates an User"
      description: "Deactivates user while on admin page. Access: ADM"
      tags:
        - "M03: Administrator"

      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                id:
                  type: integer
              required:
                - id

      responses:
        "200":
          description: "Ok. You can deactivate the profile information"
        "403":
          description: "Deactivation didnt work."

  /admin:
    get:
      operationId: R302
      summary: "R302: View admin page"
      description: "Show admin page UI. Access: ADM"
      tags:
        - "M03: Administrator"

      responses:
        "200":
          description: "Show the admin page UI"
        "403":
          description: "Did not work."

  /api/user/search:
    get:
      operationId: R303
      summary: "R303: Search Users API"
      description: "Searches for users and returns the results as JSON. Access: ADM"

      tags:
        - "M03: Administrator"

      parameters:
        - in: query
          name: query
          description: String to use for full-text search
          schema:
            type: string
          required: false
        - in: query
          name: username
          description: Username
          schema:
            type: string
          required: false

      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    username:
                      type: string

  /api/auction/search:
    get:
      operationId: R401
      summary: "R401: Search Auctions API"
      description: "Searches for auctions and returns the results as JSON. Access: VST"

      tags:
        - "M04: Auctions and Bids"

      parameters:
        - in: query
          name: query
          description: String to use for full-text search
          schema:
            type: string
          required: false
        - in: query
          name: category
          description: Category of the auctions
          schema:
            type: string
          required: false
        - in: query
          name: owner
          description: Boolean with the owner flag value
          schema:
            type: boolean
          required: false

      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    title:
                      type: string
                    owner:
                      type: string
                    category:
                      type: string
                    lastbid:
                      type: integer

  /api/auction/create:
    get:
      operationId: R402
      summary: "R402: Create Auction Page"
      description: "Provide create auction page. Access: USR"
      tags:
        - "M04: Auctions and Bids"
      responses:
        "200":
          description: "Show auction create UI."

    post:
      operationId: R403
      summary: "R403- Create auction action."
      description: "Create auction. Access: OWN"

      tags:
        - "M04: Auctions and Bids"

      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                content:
                  type: string
                media:
                  type: string
                  format: binary
                category:
                  type: string

      responses:
        "302":
          description: "Redirect after processing the new auction information."
          headers:
            Location:
              schema:
                type: string
              examples:
                302Success:
                  description: "Successful auction create. Redirect back."
                302Failure:
                  description: "Failed. Redirect back."

  /api/bid:
    post:
      operationId: R404
      summary: "R404- Bid action."
      description: "Bid. Access: USR"

      tags:
        - "M04: Auctions and Bids"

      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                value:
                  type: integer

      responses:
        "302":
          description: "Redirect after processing the new bid information."
          headers:
            Location:
              schema:
                type: string
              examples:
                302Success:
                  description: "Successful bid. Redirect back."
                302Failure:
                  description: "Failed. Redirect back."

  /auction/{id}:
    get:
      operationId: R405
      summary: "R405: View auction."
      description: "Show the auction. Access: USR"
      tags:
        - "M04: Auctions and Bids"

      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true

      responses:
        "200":
          description: "Show auctions UI"

  /api/auction/remove:
    post:
      operationId: R406
      summary: "R406- Removes an Auction"
      description: "Deletes an Auction. Access: OWN, ADM"
      tags:
        - "M04: Auctions and Bids"

      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                id:
                  type: integer
              required:
                - id

      responses:
        "200":
          description: "Auction can be removed."
        "400":
          description: "Auction cannot be removed."

  /auction/showAuctions:
    get:
      operationId: R407
      summary: "R407: Show all auctions."
      description: "Show all auctions. Access: USR"
      tags:
        - "M04: Auctions and Bids"

      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true

      responses:
        "200":
          description: "Show all auctions UI"

  /auction/{id}/edit:
    get:
      operationId: R408
      summary: "R408: Edit Auction Form"
      description: "Provide edit auction form. Access: OWN"
      tags:
        - "M04: Auctions and Bids"
      responses:
        "200":
          description: "Show edit auction UI."
    post:
      operationId: R409
      summary: "R409: Edit Auction Action"
      description: "Processes the edit auction form submission. Access: OWN"
      tags:
        - "M04: Auctions and Bids"

      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
                category:
                  type: string
                description:
                  type: string
                location:
                  type: string

      responses:
        "302":
          description: "Redirect after processing the edit auction information."
          headers:
            Location:
              schema:
                type: string
              examples:
                302Success:
                  description: "Successful auction edited. Redirect to auction page."
                  value: "/auction/{id}"
                302Failure:
                  description: "Failed auction edited. Redirect to same auction page"
                  value: "/auction/{id}/edit"
